name: Run Repository Analysis

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "GitHub repository URL to analyze"
        required: true
        default: "https://github.com/octocat/Hello-World"
      branch:
        description: "Branch name"
        required: true
        default: "main"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from test"