name: Run Repository Analysis

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: "GitHub repository URL to analyze"
        required: true
        default: "https://github.com/mandoobaba2/cowsay"
      branch:
        description: "Branch name"
        required: true
        default: "master"

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: debug ls -al (Caller Workflow)
        shell: bash
        run: |
          ls -al
          
      - name: debug pwd (Caller Workflow)
        shell: bash
        run: |
          pwd

      - name: Run external analyze action
        id: analyze
        uses: mandoobaba2/ondemand-analysis-action@main
        with:
          repo_url: ${{ github.event.inputs.repo_url }}
          branch: ${{ github.event.inputs.branch }}
          ondemand_api_key: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMjAiLCJpc3MiOiJvbmRlbWFuZCIsInRva2VuSWQiOjM2LCJ1c2VybmFtZSI6InRlc3R1c2VybWluIiwicm9sZXMiOiJVU0VSIiwiZXhwIjoxOTc3NTQyNjQwfQ.TDsalhu-VQx4HzXCrf-v7AlEpnnFXHVvWViH67JLAoUWn_4N8agX7Dz2jUBPK89uwd3YvqJLuvbcWt8cmHT4Xg

      - name: Print output variables
        run: |
          echo "result_summary:"
          echo "${{ steps.analysis.outputs.result_summary }}"
          echo "report_path:"
          echo "${{ steps.analysis.outputs.report_path }}"

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: analysis-report
          path: ${{ steps.analyze.outputs.report_path }}
      
      - name: Print JSON summary
        run: echo "${{ steps.analyze.outputs.result_summary }}"